# Estágio de Build (Compilação)
FROM maven:3.9.6-eclipse-temurin-21 AS build
COPY src/main/java/br/com/ifba/mapadocorreapi .
RUN mvn clean package -DskipTests

# Estágio de Execução
FROM eclipse-temurin:21-jdk-jammy
COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]